/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Control.Control;
import LogicaDeNegocio.Modelo;
import LogicaDeNegocio.Usuario;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author juanmurillo
 */
public class InterfazAerolinea extends javax.swing.JFrame {

    private Modelo modelo;
    private Control control;
    /**
     * Creates new form InterfazAerolinea
     */
    public InterfazAerolinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnUsuario = new javax.swing.JButton();
        jbtnUsuario1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnUsuario.setText("Crear un Usuario");

        jbtnUsuario1.setText("Mostrar los usuarios");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(642, Short.MAX_VALUE)
                .addComponent(jbtnUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnUsuario)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUsuario)
                    .addComponent(jbtnUsuario1))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAerolinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtnUsuario;
    private javax.swing.JButton jbtnUsuario1;
    // End of variables declaration//GEN-END:variables

    public void setModel(Modelo model) {
        this.modelo = model;
    }

    public void setController(Control control) {
        this.control = control;
        jbtnUsuario.addMouseListener(control);
        jbtnUsuario1.addMouseListener(control);

    }

    public String obtenerDatosUsuario() {
        String x = "";
        System.out.println("Opcion");
        InterfazUsuario interfaz = new InterfazUsuario();
        String [] botonesT = { "Guardar", "Cancelar"};
        Object [] botones = { "Guardar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null, interfaz , "Usuario", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null/*icono*/,botonesT,botones);
        if (JOptionPane.OK_OPTION == option) {
            try{
                AccesoADatos.AccesoADatos.insertarUsuario(interfaz.crearUsuario());
            }
            catch(Exception e){
            }
        }
        
        return x;
    }
    
    public void mostrarDatosUsuario() {
        InterfazListaUsuarios interfaz = new InterfazListaUsuarios(AccesoADatos.AccesoADatos.buscarUsuarios());
            try{
                JOptionPane.showMessageDialog(null, interfaz);
            }
            catch(Exception e){
            }
    }

    public JButton botonUsuario(){
        return jbtnUsuario;
    } 
    
    public JButton botonUsuario1(){
        return jbtnUsuario1;
    } 
    
    private void AccesoADatos() {
    }
    
}
